### ISSUE TITLE
Dados de 2016

### ISSUE THREAD

**Issue by gustavodemari** [thevtm/CartolaFCDados#1]
Por gentileza, @thevtm , poderia disponibilizar os dados de 2016?

Tentei pegar diretamente no Scraper no Morph, mas só tem os dados de 2017.

Obrigado.

**Comment by thevtm** [comment]
Ola, desculpe a demora, ando meio ocupado.
Adicionei os dados de 2016 ao repositorio.
Segue em anexo os dados do morph de 2016, porém não estão completos.

[CartolaFCScraper 2016.zip](https://github.com/thevtm/CartolaFCDados/files/1048980/CartolaFCScraper.2016.zip)

**Comment by gustavodemari** [comment]
Obrigado @thevtm
