### ISSUE TITLE
Dados de 2017

### ISSUE THREAD

**Issue by marlesson** [thevtm/CartolaFCDados#2]
Olá,

Você teria os dados de 2017? 
Vi o projeto do crawler (CartolaFCScraper), mas não encontrei o script que formata os dados do crawler para o formato do CartolaFCDados aqui no repositório. Teria como disponibilizar ?

Agradeço.

**Comment by thevtm** [comment]
Olá

Adicionei o script ao repositório, escrevi para o formato de 2016, talvez precise modificar.

:smiley:

**Comment by d03099300** [comment]
> Olá
> 
> Adicionei o script ao repositório, escrevi para o formato de 2016, talvez precise modificar.

Alguém sabe colocar essa barra em um site aonde acesso aos dados do cartola fc
![Screenshot_20200130-132837_Samsung Internet](https://user-images.githubusercontent.com/60477823/73469505-35b47c00-4365-11ea-90e4-f6aedea539dc.jpg)
